<a href="https://colab.research.google.com/github/eerenkurt/AutoGallerySystem/blob/main/05-regression-error-metrics/insurance_cost_error_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

In [ ]:
df = pd.read_csv("insurance.csv")

In [ ]:
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [ ]:
df = pd.get_dummies(df, columns = ["sex","smoker","region"], drop_first=True)

In [ ]:
df.head(3)

   age    bmi  children  ...  region_northwest  region_southeast  region_southwest
0   19  27.90         0  ...             False             False              True
1   18  33.77         1  ...             False              True             False
2   28  33.00         3  ...             False              True             False

[3 rows x 9 columns]

In [ ]:
y = df["charges"]
x = df.drop("charges", axis = 1)

In [ ]:
lm = LinearRegression()
model = lm.fit(x,y)

In [ ]:
model.score(x,y)

0.7509130345985207

In [ ]:
model.predict([[19,26,0,1,1,0,0,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([24517.93110714])

In [ ]:
df_hata = pd.DataFrame()

In [ ]:
df_hata["y"] = y

In [ ]:
y_tahmin = model.predict(x)

In [ ]:
df_hata["tahmin"] = y_tahmin

In [ ]:
df_hata["error"] = y-y_tahmin

In [ ]:
df_hata.head(10)

             y        tahmin         error
0  16884.92400  25293.713028  -8408.789028
1   1725.55230   3448.602834  -1723.050534
2   4449.46200   6706.988491  -2257.526491
3  21984.47061   3754.830163  18229.640447
4   3866.85520   5592.493386  -1725.638186
5   3756.62160   3719.825799     36.795801
6   8240.58960  10659.961225  -2419.371625
7   7281.50560   8047.910607   -766.405007
8   6406.41070   8502.973920  -2096.563220
9  28923.13692  11884.637518  17038.499402

In [ ]:
df_hata["squared_error"] = df_hata["error"]**2

In [ ]:
df_hata.head(10)

             y        tahmin         error  squared_error
0  16884.92400  25293.713028  -8408.789028   7.070773e+07
1   1725.55230   3448.602834  -1723.050534   2.968903e+06
2   4449.46200   6706.988491  -2257.526491   5.096426e+06
3  21984.47061   3754.830163  18229.640447   3.323198e+08
4   3866.85520   5592.493386  -1725.638186   2.977827e+06
5   3756.62160   3719.825799     36.795801   1.353931e+03
6   8240.58960  10659.961225  -2419.371625   5.853359e+06
7   7281.50560   8047.910607   -766.405007   5.873766e+05
8   6406.41070   8502.973920  -2096.563220   4.395577e+06
9  28923.13692  11884.637518  17038.499402   2.903105e+08

In [ ]:
df_hata["abs_error"] = np.abs(df_hata["error"])

In [ ]:
df_hata.head(10)

             y        tahmin         error  squared_error     abs_error
0  16884.92400  25293.713028  -8408.789028   7.070773e+07   8408.789028
1   1725.55230   3448.602834  -1723.050534   2.968903e+06   1723.050534
2   4449.46200   6706.988491  -2257.526491   5.096426e+06   2257.526491
3  21984.47061   3754.830163  18229.640447   3.323198e+08  18229.640447
4   3866.85520   5592.493386  -1725.638186   2.977827e+06   1725.638186
5   3756.62160   3719.825799     36.795801   1.353931e+03     36.795801
6   8240.58960  10659.961225  -2419.371625   5.853359e+06   2419.371625
7   7281.50560   8047.910607   -766.405007   5.873766e+05    766.405007
8   6406.41070   8502.973920  -2096.563220   4.395577e+06   2096.563220
9  28923.13692  11884.637518  17038.499402   2.903105e+08  17038.499402

In [ ]:
df_hata["percent_error"] = np.abs((y-y_tahmin)/y)

In [ ]:
df_hata.head(10)

             y        tahmin  ...     abs_error  percent_error
0  16884.92400  25293.713028  ...   8408.789028       0.498006
1   1725.55230   3448.602834  ...   1723.050534       0.998550
2   4449.46200   6706.988491  ...   2257.526491       0.507371
3  21984.47061   3754.830163  ...  18229.640447       0.829205
4   3866.85520   5592.493386  ...   1725.638186       0.446264
5   3756.62160   3719.825799  ...     36.795801       0.009795
6   8240.58960  10659.961225  ...   2419.371625       0.293592
7   7281.50560   8047.910607  ...    766.405007       0.105254
8   6406.41070   8502.973920  ...   2096.563220       0.327260
9  28923.13692  11884.637518  ...  17038.499402       0.589096

[10 rows x 6 columns]

In [ ]:
df_hata.mean()

y                1.327042e+04
tahmin           1.327042e+04
error            2.289371e-12
squared_error    3.650189e+07
abs_error        4.170887e+03
percent_error    4.203527e-01
dtype: float64

In [ ]:
mean_squared_error(y,y_tahmin)

36501893.00741544

In [ ]:
mean_absolute_error(y,y_tahmin)

4170.886894163586

In [ ]:
mean_absolute_percentage_error(y,y_tahmin)

0.4203526847372702