<a href="https://colab.research.google.com/github/eerenkurt/AutoGallerySystem/blob/main/03-data-preprocessing-and-encoding/car_price_prediction_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv("audi.csv")

In [ ]:
# y = ax + b

In [ ]:
df.head(3)

,index,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),href,PPY,MileageRank,PriceRank,PPYRank,Score
0,0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,https://www.autotrader.co.uk/car-details/20221...,2499.166667,215,163,340,718
1,4,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,https://www.autotrader.co.uk/car-details/20221...,2688.750000,222,330,276,828
2,7,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,https://www.autotrader.co.uk/car-details/20221...,3599.666667,221,327,94,642

In [ ]:
df = df.drop(columns = ["index", "href", "MileageRank", "PriceRank", "PPYRank", "Score" ])

In [ ]:
df.head(3)

,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),PPY
0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 471 entries, 0 to 470
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              471 non-null    float64
 1   Type              471 non-null    object
 2   Mileage(miles)    471 non-null    float64
 3   Engine            471 non-null    object
 4   PS                471 non-null    float64
 5   Transmission      471 non-null    object
 6   Fuel              471 non-null    object
 7   Number_of_Owners  471 non-null    int64
 8   Price(£)          471 non-null    float64
 9   PPY               471 non-null    float64
dtypes: float64(5), int64(1), object(4)
memory usage: 36.9+ KB

In [ ]:
df.head(3)

,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),PPY
0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [ ]:
df.columns = ["yil","kasa","mil","motor","ps","vites","yakit","sahip","fiyat","ppy"]

In [ ]:
df.head(3)

,yil,kasa,mil,motor,ps,vites,yakit,sahip,fiyat,ppy
0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [ ]:
df["motor"] = df["motor"].str.replace("L","")

In [ ]:
df["motor"] = pd.to_numeric(df["motor"])

In [ ]:
df.head(3)

,yil,kasa,mil,motor,ps,vites,yakit,sahip,fiyat,ppy
0,2018.0,Hatchback,44000.0,1.6,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [ ]:
df = pd.get_dummies(df,columns = ["kasa","vites","yakit"],drop_first = True,)

In [ ]:
df.head(3)

,yil,mil,motor,ps,sahip,fiyat,ppy,vites_Manual,yakit_Petrol
0,2018.0,44000.0,1.6,114.398422,1,14995.0,2499.166667,True,False
1,2016.0,42596.0,1.0,93.688363,3,10755.0,2688.750000,True,True
2,2015.0,42700.0,1.4,123.274162,2,10799.0,3599.666667,True,True

In [ ]:
y = df["fiyat"]
x = df.drop("fiyat",axis = 1)

In [ ]:
lm = LinearRegression()
model = lm.fit(x,y)

In [ ]:
model.predict([[2017,30000,1.6,110,1,2600,0,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([13145.9080419])

In [ ]:
model.score(x,y)

0.9595295772839731